const LEARN={
var:["Tipos de variável",`<p>Variável é todo dado diretamente observável que pode ser quantificado. Um <b>dado</b> (20) só vira <b>informação</b> (20 anos) quando ganha contexto.</p>
<h4>Qualitativas (categóricas)</h4><ul><li><b>Nominal:</b> categorias sem hierarquia (tipo sanguíneo, cor favorita).</li><li><b>Ordinal:</b> categorias com ordem (classe da insuficiência cardíaca, escolaridade).</li><li><b>Binária:</b> nominal ou ordinal com apenas duas categorias (fumante/não fumante).</li></ul>
<h4>Quantitativas (numéricas)</h4><ul><li><b>Contínuas:</b> uma “régua infinitesimal” (pressão arterial, hemoglobina).</li><li><b>Discretas:</b> uma “régua com marcas”, contagens (número de infartos, de consultas).</li></ul>
<div class="trap"><h4>Na dúvida, colete contínuo</h4><p>O teste estatístico depende do tipo de variável. Do IMC numérico chega-se a eutrófico, sobrepeso e obeso; o caminho inverso é impossível.</p></div>`],
descr:["Como descrever variáveis",`<ul><li><b>Qualitativa:</b> frequência e proporção (%), com gráfico de barras.</li><li><b>Quantitativa simétrica (normal):</b> média ± desvio padrão, com histograma.</li><li><b>Quantitativa assimétrica:</b> mediana [intervalo interquartil], com boxplot.</li></ul>
<p>Sempre relate tendência central e dispersão juntas. <b>Uma sem a outra é meia-verdade.</b></p>`],
centro:["Medidas de tendência central",`<h4>Média</h4><p>Soma de todos os valores dividida pelo número de valores. Usa todos os dados, e por isso é sensível a valores extremos.</p>
<h4>Mediana</h4><p>O valor do meio, depois de ordenar os dados (rol). Com número par de valores, é a média dos dois centrais. É pouco sensível a outliers e serve também para variáveis ordinais.</p>
<h4>Moda</h4><p>O valor mais frequente. Serve para qualquer tipo de variável (ex.: tipo sanguíneo mais comum), mas com frequências baixas representa pouco.</p>
<div class="trap"><h4>Experimente</h4><p>No exemplo da internação, um único paciente com 120 dias leva a média a 21,4 dias, enquanto a mediana fica em 5. No exemplo dos salários, os sócios fazem a média de uma empresa de vendedores passar de R$ 400 mil. Arraste um ponto e veja: a mediana quase não se move.</p></div>`],
box:["Quartis, IIQ e boxplot",`<p>A mediana divide os dados em duas metades. Os quartis são as medianas dessas metades: <b>Q1</b> (25%) e <b>Q3</b> (75%).</p>
<p><b>Intervalo interquartil (IIQ) = Q3 − Q1</b>: a amplitude dos 50% centrais, sem a influência dos extremos.</p>
<h4>Boxplot de Tukey (moderno)</h4><ul><li>A caixa vai de Q1 a Q3; a linha interna é a mediana.</li><li>Limites (“mínimo e máximo virtuais”): Q1 − 1,5 × IIQ e Q3 + 1,5 × IIQ.</li><li>As hastes vão até os valores mais extremos <i>dentro</i> dos limites.</li><li>O que fica fora é marcado como ponto: outlier.</li></ul>
<p>O boxplot <b>original</b> estende as hastes até o mínimo e o máximo reais, o que pode distorcer a percepção da dispersão.</p>
<div class="trap"><h4>Métodos diferentes, quartis diferentes</h4><p>Existem vários jeitos de calcular quartis. Na bancada você pode escolher: mediana de cada metade sem a mediana (o mais usado em aula), com a mediana, ou por interpolação (o método do Excel, do R e do jamovi). Com poucos dados, os resultados podem diferir um pouco; com muitos dados, praticamente coincidem.</p></div>`],
dp:["Variância e desvio padrão",`<p><b>Variância:</b> a média dos desvios ao quadrado, ou seja, o quanto os dados se distanciam da média, em média. Os desvios são elevados ao quadrado porque, somados, sempre dão zero.</p>
<ul><li>Variância <b>populacional</b>: divide por n.</li><li>Variância <b>amostral</b>: divide por n − 1, porque a média da amostra já “usou” uma parte da informação.</li></ul>
<p><b>Desvio padrão = √variância.</b> Volta à mesma unidade da média (kg, não kg²).</p>
<p>Para proporções (duas categorias): DP = √(p(1 − p)).</p>`],
cv:["Coeficiente de variação",`<p><b>CV% = DP ÷ média × 100.</b> Mede a dispersão relativa à média e permite comparar grupos com médias muito diferentes.</p>
<p>Prematuros (1,5 ± 0,3 kg) têm CV de 20%; adultos obesos (120 ± 15 kg), 12,5%. Em quilos, os adultos variam 50 vezes mais; em termos relativos, os prematuros variam mais.</p>
<p>Quando as medidas têm grandezas diferentes, uma alternativa é o coeficiente de dispersão relativa: CDR = DP ÷ (amplitude/2) × 100.</p>`],
dist:["Distribuição normal e assimetria",`<p>A distribuição normal é simétrica, em forma de sino, com média, mediana e moda coincidindo no pico. Fica definida por apenas dois parâmetros: média (μ) e desvio padrão (σ). A área sob a curva é 1: <b>áreas são probabilidades</b>.</p>
<h4>Regra 68–95–99,7</h4><p>Numa normal, cerca de 68% dos valores ficam a até 1 DP da média, 95% a até 2 DP e 99,7% a até 3 DP. Ative a regra e compare com distribuições assimétricas.</p>
<h4>Assimetria e curtose</h4><ul><li><b>Assimetria</b>: 0 é simétrica; positiva, cauda longa à direita; negativa, à esquerda.</li><li><b>Curtose</b>: 0 é a da normal; positiva, mais pontiaguda; negativa, mais achatada.</li></ul>
<p>Aproximadamente normais: altura, pressão arterial, hemoglobina. Assimétricas: triglicerídeos, tempo de internação, carga viral. Na assimetria à direita, a média é puxada para a cauda longa: prefira mediana e IIQ.</p>`],
and:["Regra do “E”",`<p>Probabilidade de A <b>e</b> B acontecerem juntos = P(A) × P(B | A). Como P(B | A) é no máximo 1, o resultado nunca passa de P(A).</p>
<p>“Um pedaço de um pedaço é um pedaço menor.” A descrição de Larissa torna “feminista” plausível, e a mente troca probabilidade por semelhança com um estereótipo. É a falácia da conjunção, descrita por Tversky e Kahneman.</p>
<div class="trap"><h4>Na clínica</h4><p>Histórias muito detalhadas parecem mais convincentes, mas cada detalhe acrescentado <i>reduz</i> a probabilidade do conjunto.</p></div>`],
or:["Regra do “OU”",`<p>P(A ou B) = P(A) + P(B) − P(A e B). O último termo evita contar duas vezes quem tem as duas condições.</p><p>Se A e B forem mutuamente exclusivos (não podem ocorrer juntos), P(A e B) = 0 e basta somar.</p>`],
odds:["Probabilidade e chance",`<ul><li><b>Probabilidade</b> (risco, prevalência): fração de vezes que algo acontece → X ÷ total. Vai de 0 a 1.</li><li><b>Chance</b> (<i>odds</i>): ocorrências divididas por não ocorrências → X ÷ (total − X). Vai de 0 ao infinito.</li></ul>
<p>Com eventos raros, as duas ficam parecidas (20 em 1.000: 0,020 e 0,020). Com eventos frequentes, divergem muito (80 em 100: 0,8 e 4). É por isso que a odds ratio exagera o risco relativo quando o desfecho é comum.</p>`],
pct:["Porcentagens se multiplicam",`<p>Cortar 25% e depois aumentar 25% não devolve o preço original: 100 × 0,75 × 1,25 = 93,75. O aumento incide sobre uma base menor.</p><p>Na saúde, o mesmo raciocínio vale para reduções relativas: duas reduções de 50% seguidas não somam 100%, resultam em 75%.</p>`],
tcl:["Teorema Central do Limite",`<p>Se você tirar muitas amostras aleatórias de uma população, de qualquer formato, e calcular a média de cada uma, a distribuição dessas médias se aproxima de uma normal centrada em μ, com desvio padrão <b>σ/√n</b>, à medida que n cresce.</p>
<p>“Não importa como é a população: médias de amostras grandes o suficiente se comportam como se fossem normais.” Para populações muito assimétricas, n acima de 30 costuma bastar.</p>
<div class="trap"><h4>Por que isso importa</h4><p>É o TCL que permite construir intervalos de confiança e testes para médias mesmo quando os dados individuais não são normais.</p></div>`],
ep:["Desvio padrão × erro padrão",`<ul><li><b>DP</b>: quanto os indivíduos variam em torno da média. Descreve os dados e <i>não</i> diminui com n.</li><li><b>EP = DP ÷ √n</b>: quanto a média amostral varia de amostra para amostra. Mede a precisão da estimativa e diminui com √n.</li></ul>
<p>Para <b>descrever</b>: média (DP). Para <b>inferir</b>: média (IC 95%).</p><p>Exemplo: PAS média 128 mmHg, DP 15, n = 100 → EP = 1,5 → IC 95% de 125,1 a 130,9 mmHg.</p>`],
amostr:["Tipos de amostragem",`<ul><li><b>Aleatória simples:</b> todos têm a mesma probabilidade de sorteio. Sem viés, mas exige a lista completa da população.</li><li><b>Estratificada:</b> sorteia dentro de cada estrato (ex.: jovens e idosos). Garante a representação dos subgrupos e costuma ser mais precisa.</li><li><b>Conglomerados:</b> sorteia grupos inteiros (bairros, escolas). Prática e barata, mas menos precisa quando os grupos diferem entre si.</li><li><b>Conveniência:</b> quem está disponível. Rápida, com alto risco de viés de seleção.</li><li><b>Intencional, por cotas, bola de neve:</b> não probabilísticas; úteis em situações específicas, mas a generalização fica comprometida.</li></ul>
<div class="trap"><h4>Viés não se corrige com mais amostras</h4><p>Repetir a amostragem por conveniência 500 vezes dá sempre o mesmo erro. Aumentar n reduz o erro aleatório, não o sistemático.</p></div>`],
ic:["Intervalo de confiança",`<p>Uma <b>estimativa pontual</b> é um único número calculado na amostra. Uma <b>estimativa intervalar</b> é uma faixa de valores plausíveis para o parâmetro, construída por um método com confiança conhecida.</p>
<p>“95% de confiança” descreve o <b>método</b>: se o estudo fosse repetido muitas vezes, cerca de 95% dos intervalos conteriam o valor verdadeiro. Um intervalo específico contém ou não contém; não sabemos qual.</p>
<div class="trap"><h4>Não confunda</h4><p>O IC é sobre o parâmetro (a média da população), não sobre onde ficam os valores individuais.</p></div>
<p>Com amostras pequenas, a fórmula com z produz intervalos estreitos demais. A distribuição t corrige isso.</p>`],
iccalc:["Como calcular o IC",`<div class="f">Médias: IC = M ± z × DP ÷ √n<br>Proporções: IC = p ± z × √(p(1 − p) ÷ n)</div>
<p>z = 1,645 (90%), 1,96 (95%), 2,576 (99%). Quanto maior z, maior a confiança e mais largo o intervalo.</p>
<h4>De onde vem o cálculo da amostra</h4><p>A margem de erro é e = z × √(p(1 − p) ÷ n). Isolando n:</p><div class="f">n = z² × p(1 − p) ÷ e²</div><p>Com z ≈ 2, e = 5% e p = 50% (o pior caso), n = 400.</p>`],
icwidth:["O que muda a largura do IC",`<p>A largura é proporcional a DP ÷ √n e aumenta com a confiança.</p><ul><li>Mais variabilidade (DP maior) → IC mais largo.</li><li>Mais participantes → IC mais estreito, mas só com a raiz: para reduzir a largura pela metade, é preciso quadruplicar n.</li><li>Mais confiança (99%) → IC mais largo.</li></ul>`],
cha:["Fisher e o chá",`<p>Muriel Bristol disse a Ronald Fisher que sabia distinguir se o leite tinha sido posto antes ou depois do chá. Fisher preparou 8 xícaras, 4 de cada tipo.</p>
<p><b>H₀</b>: ela não sabe distinguir (acerta por acaso). Há 70 formas de escolher 4 xícaras entre 8; só uma acerta todas. Acertar as quatro por puro acaso: 1/70 = 1,4%.</p>
<p>Esse é o raciocínio do valor de p: quão surpreendente seria o resultado se nada estivesse acontecendo?</p>`],
p:["O que é, e o que não é, o valor de p",`<p>Probabilidade de obter resultados iguais ou mais extremos que os observados, <b>supondo que H₀ seja verdadeira</b> (e que o modelo esteja correto).</p>
<p>Com α = 0,05, rejeita-se H₀ se p ≤ 0,05, aceitando até 5% de falsos positivos quando H₀ é verdadeira. É uma convenção, não uma lei da natureza.</p>
<div class="trap"><h4>O valor de p NÃO é</h4><ul><li>a probabilidade de H₀ ser verdadeira;</li><li>a probabilidade de o resultado ser “obra do acaso”;</li><li>uma medida do tamanho ou da importância do efeito.</li></ul><p>p > 0,05 não demonstra ausência de efeito, e p < 0,05 não garante replicação. p = 0,049 e p = 0,051 dizem praticamente a mesma coisa. Relate o valor exato (ou p < 0,001), nunca “p = 0,000”.</p></div>
<p class="src">Wasserstein RL, Lazar NA. The ASA statement on p-values. Am Stat 2016. · Greenland S et al. Eur J Epidemiol 2016.</p>`],
poder:["α, β e poder",`<table class="t"><thead><tr><th>Decisão</th><th>H₀ verdadeira</th><th>H₀ falsa</th></tr></thead><tbody><tr><td>Rejeitar H₀</td><td class="no">Erro tipo I (α)</td><td class="ok">Acerto (poder)</td></tr><tr><td>Não rejeitar H₀</td><td class="ok">Acerto</td><td class="no">Erro tipo II (β)</td></tr></tbody></table>
<ul><li><b>α</b>: fixado antes do estudo (por convenção, 0,05).</li><li><b>β</b>: chance de não detectar um efeito que existe; em geral planeja-se entre 0,10 e 0,20.</li><li><b>Poder = 1 − β</b>: aumenta com n maior, efeito verdadeiro maior, menor variabilidade e α maior.</li></ul>
<div class="trap"><h4>Poder se calcula antes</h4><p>O poder é propriedade do delineamento. O “poder post hoc”, calculado com o efeito observado, é apenas uma releitura do próprio p.</p></div>`],
mult:["Múltiplas comparações",`<p>Com um teste e α = 0,05, a chance de falso positivo é 5% quando H₀ é verdadeira. Com k testes independentes, a chance de <b>pelo menos um</b> falso positivo é 1 − 0,95<sup>k</sup>: 23% com 5 testes, 40% com 10, 64% com 20.</p>
<p>“Quanto mais você procura, mais você acha, mesmo quando não há nada para achar.”</p>`],
correc:["Como lidar",`<ul><li><b>Planejar:</b> definir o desfecho primário e as análises antes da coleta e registrar o protocolo.</li><li><b>Corrigir:</b> Bonferroni (α ÷ k; simples, conservador), Holm (sequencial, sempre mais poderoso que Bonferroni), Benjamini–Hochberg (controla a taxa de falsas descobertas; útil com muitos testes exploratórios).</li><li><b>Comunicar:</b> informar quantos testes foram feitos e tratar subgrupos como exploratórios.</li></ul>
<p>Ative “3 efeitos reais” e rode 1.000 vezes: veja como cada correção troca falsos positivos por poder.</p>`],
rel:["Significância × relevância",`<p>O Δ mínimo clinicamente importante é o menor efeito que mudaria a conduta ou faria diferença para o paciente. Ele deve ser definido <b>antes</b>, com base clínica, e não a partir dos dados.</p>
<ul><li>IC inteiro acima do Δ: significativo e relevante.</li><li>IC acima de zero, mas inteiro abaixo do Δ: significativo e trivial (típico de amostras enormes).</li><li>IC acima de zero, cruzando o Δ: relevância incerta.</li><li>IC largo, cruzando o zero e o Δ: inconclusivo, não “sem efeito”.</li><li>IC estreito, cruzando o zero, abaixo do Δ: evidência contra efeito relevante.</li></ul>`],
same:["Ausência de evidência",`<p>“Ausência de evidência não é evidência de ausência” (Altman e Bland, 1995). Dois estudos com a mesma estimativa, um preciso e outro impreciso, não se contradizem.</p><p>Uma análise de 791 artigos em cinco periódicos encontrou que 51% interpretaram “não significativo” como “sem efeito” (Amrhein, Greenland e McShane, Nature 2019).</p>`],
ratio:["Razões com IC",`<ul><li><b>= 1:</b> ausência de associação.</li><li><b>> 1:</b> associação positiva; o desfecho é mais frequente nos expostos.</li><li><b>< 1:</b> associação negativa; possível fator de proteção.</li></ul>
<p>Um IC 95% que não inclui 1 corresponde, aproximadamente, a p < 0,05. Mas a largura do IC, a precisão, importa tanto quanto isso. Razões são mostradas em escala logarítmica, onde 0,5 e 2 ficam à mesma distância de 1.</p>`],
teste:["Escolhendo o teste",`<h4>Paramétrico × não paramétrico</h4><p>Testes paramétricos (t, ANOVA, Pearson) supõem distribuição aproximadamente normal e têm mais poder. Os não paramétricos (Mann–Whitney, Wilcoxon, Kruskal–Wallis, Spearman) exigem menos pressupostos e servem para dados assimétricos, ordinais ou amostras pequenas.</p>
<h4>Por que Welch por padrão</h4><p>O t de Welch perde muito pouco quando as variâncias são iguais e protege quando não são, dispensando o pré-teste de Levene (Delacre, Lakens e Leys, 2017).</p>
<h4>Por que não vários testes t?</h4><p>Comparar três grupos com três testes t infla o erro tipo I. Para isso existe a ANOVA.</p>`],
};
const TL=(t,what,h0,when,ex,read,also)=>[t,`<p>${what}</p><h4>Hipóteses</h4><p>${h0}</p><h4>Quando usar</h4><p>${when}</p><h4>Exemplo</h4><p>${ex}</p><h4>Como ler o resultado</h4><p>${read}</p>${also?`<div class="trap"><h4>Atenção</h4><p>${also}</p></div>`:""}`];
Object.assign(LEARN,{
bancada:["A bancada de dados",`<p>Um lugar para experimentar com qualquer conjunto de números. Tudo é recalculado a cada mudança.</p><h4>Experimentos sugeridos</h4><ul><li>Acrescente um valor extremo e compare quanto se movem a média, a mediana, o DP e o IIQ.</li><li>Some 10 a todos os valores: o centro muda, a dispersão não.</li><li>Multiplique todos por 2: o centro e o DP dobram, o CV não muda.</li><li>Aplique o logaritmo em dados assimétricos (triglicerídeos) e veja a distribuição ficar simétrica.</li><li>Duplique os dados: média e DP quase não mudam, mas o erro padrão e o IC encolhem.</li><li>Ative “Estime antes de ver” e treine o olho antes de conferir.</li></ul><p>Os dados podem ser colados de uma planilha: uma coluna do Excel vira uma lista de valores.</p>`],
qq:["Gráfico Q-Q e normalidade",`<p>O gráfico Q-Q compara cada valor observado (eixo vertical) com o valor que seria esperado numa distribuição normal de mesma média e DP (eixo horizontal, em escores z).</p><ul><li><b>Pontos sobre a linha:</b> dados compatíveis com a normal.</li><li><b>Curva em forma de banana:</b> assimetria.</li><li><b>Pontas que fogem da linha:</b> caudas pesadas ou outliers.</li></ul><h4>Shapiro-Wilk</h4><p>Testa H₀: “os dados vêm de uma distribuição normal”. p pequeno indica desvio da normalidade.</p><div class="trap"><h4>Cuidado</h4><p>Com amostras pequenas, o teste quase nunca rejeita a normalidade (pouco poder). Com amostras grandes, rejeita desvios mínimos e irrelevantes. Por isso, olhe sempre o gráfico junto com o p.</p></div>`],
zscore:["Escore z e percentis",`<p><b>z = (valor − média) ÷ DP.</b> Diz quantos desvios padrão um valor está acima (z positivo) ou abaixo (z negativo) da média.</p><p>O escore z permite comparar medidas de escalas diferentes, como notas de provas diferentes ou o peso de um bebê com a curva de referência.</p><p>Na distribuição normal, cada z corresponde a um percentil: z = 0 é o percentil 50; z = 1,645 é o 95; z = 1,96 deixa 2,5% em cada cauda.</p><p>Curvas de crescimento infantil usam exatamente isso: o escore z do peso ou da altura para a idade.</p>`],
lln:["Lei dos grandes números",`<p>À medida que o número de repetições cresce, a proporção observada se aproxima da probabilidade verdadeira.</p><div class="trap"><h4>Falácia do jogador</h4><p>O acaso não tem memória. Depois de cinco caras seguidas, a próxima jogada continua com 50% de chance. A proporção se aproxima de 50% porque as novas jogadas “diluem” as antigas, não porque o acaso compensa.</p></div><p>É por isso que amostras grandes estimam melhor: pequenas amostras oscilam muito.</p>`],
danca:["A dança dos valores de p",`<p>Se um mesmo estudo fosse repetido, com a mesma população e o mesmo efeito verdadeiro, o valor de p mudaria muito de uma repetição para outra, especialmente quando o poder é moderado.</p><p>Por isso um único p = 0,04 ou p = 0,08 não deve ser tratado como veredito. O intervalo de confiança mostra a mesma incerteza de forma mais informativa: a estimativa e a faixa de efeitos compatíveis com os dados.</p><p class="src">Cumming G. Replication and p intervals. Perspect Psychol Sci 2008.</p>`],
pressup:["Pressupostos",`<p>Cada teste supõe algumas condições sobre os dados. Quando elas falham muito, o p e o IC podem ficar enganosos.</p><ul><li><b>Independência:</b> cada observação vem de uma pessoa diferente (ou os pares estão identificados, nos testes pareados). É o pressuposto mais importante e não se testa com estatística: depende do desenho do estudo.</li><li><b>Normalidade:</b> para testes t e ANOVA, dos dados em cada grupo (ou das diferenças, no pareado; dos resíduos, na regressão). Com amostras grandes, o Teorema Central do Limite torna esses testes robustos.</li><li><b>Variâncias parecidas:</b> quando os DPs diferem muito, use as versões de Welch.</li><li><b>Valores esperados ≥ 5:</b> no qui-quadrado; senão, Fisher.</li></ul><p>Os testes não paramétricos exigem menos, mas também têm pressupostos (por exemplo, observações independentes).</p>`],
simul:["O mundo simulado",`<p>Na vida real, nunca conhecemos a verdade da população. Aqui você a define e o computador sorteia estudos a partir dela.</p><ul><li><b>Poder:</b> se há efeito, em quantos estudos o teste dá p < α.</li><li><b>Erro tipo I:</b> se não há efeito (botão “Sem efeito”), quantos estudos dão p < α mesmo assim. Deve ficar perto de α.</li><li><b>Paramétrico × não paramétrico:</b> compare o poder dos dois testes com dados normais, assimétricos ou com outliers.</li><li><b>Maldição do vencedor:</b> com pouco poder, os estudos que “deram certo” exageram o tamanho do efeito.</li></ul><p>Experimente mudar o tamanho da amostra e veja o poder subir.</p>`],
teste:["Escolhendo o teste",`<p>A escolha depende de três perguntas: qual o objetivo (comparar, associar, prever), quantos grupos ou momentos, e que tipo de variável é o desfecho.</p><h4>Paramétrico × não paramétrico</h4><p>Testes paramétricos (t, ANOVA, Pearson) supõem distribuição aproximadamente normal e têm mais poder quando isso vale. Os não paramétricos (Mann-Whitney, Wilcoxon, Kruskal-Wallis, Spearman) usam os postos dos valores, exigem menos pressupostos e servem para dados assimétricos, ordinais ou com outliers.</p><h4>Por que Welch por padrão</h4><p>O t de Welch perde muito pouco quando as variâncias são iguais e protege quando não são (Delacre, Lakens e Leys, 2017).</p><h4>Por que não vários testes t?</h4><p>Comparar três grupos com três testes t infla o erro tipo I. Para isso existe a ANOVA.</p><p>No laboratório, cada teste mostra os dados, a distribuição de referência, o resultado e uma frase pronta para relatar. Use o mundo simulado para comparar testes.</p>`],
t_t1:TL("t para uma amostra","Compara a média de uma amostra com um valor de referência conhecido (μ₀).","H₀: a média da população é igual a μ₀. H₁: é diferente.","Desfecho numérico, aproximadamente normal (ou n grande), e um valor de referência externo: meta, valor normal, média histórica.","A PAS média de hipertensos tratados difere da meta de 120 mmHg?","t = (média − μ₀) ÷ EP. Quanto mais longe de zero, mais incompatível com H₀. O IC da diferença mostra a faixa de diferenças compatíveis com os dados.","Se o IC 95% da média não inclui μ₀, o p é menor que 0,05."),
t_w1:TL("Wilcoxon para uma amostra","Versão por postos do t para uma amostra: compara os valores com uma referência usando a ordem das diferenças.","H₀: as diferenças em relação a μ₀ são simétricas em torno de zero (a mediana é μ₀).","Dados assimétricos, ordinais ou com outliers, especialmente com amostras pequenas.","O escore de dor mediano após o tratamento é diferente de 5?","V soma os postos das diferenças positivas. Se for muito maior ou muito menor que o esperado ao acaso, o p é pequeno. O r rank-biserial vai de −1 a 1.","Valores iguais à referência são descartados."),
t_sw:TL("Shapiro-Wilk","Testa se os dados são compatíveis com uma distribuição normal.","H₀: os dados vêm de uma distribuição normal. Aqui, p pequeno é que indica problema.","Antes de escolher entre teste paramétrico e não paramétrico, junto com o histograma e o Q-Q.","Os níveis de glicose de um grupo seguem distribuição normal?","W próximo de 1 indica normalidade. Use o mundo simulado com dados assimétricos para ver como o poder do teste depende de n.","Com n pequeno quase nunca rejeita; com n enorme rejeita desvios irrelevantes. Olhe os gráficos."),
t_bin:TL("Teste binomial","Compara uma proporção observada com uma proporção de referência, de forma exata.","H₀: a proporção na população é igual a p₀.","Desfecho sim/não em uma amostra, com referência externa (prevalência nacional, taxa esperada).","A proporção de fumantes na nossa amostra difere dos 15% da população geral?","O p soma as probabilidades de todos os resultados tão ou menos prováveis que o observado, se p₀ fosse verdadeira. O IC de Wilson mostra a faixa de proporções compatíveis.",""),
t_tind:TL("t para amostras independentes","Compara as médias de dois grupos formados por pessoas diferentes.","H₀: as médias das duas populações são iguais.","Desfecho numérico e um fator com dois grupos independentes. Use Welch (padrão) quando os DPs forem diferentes.","A PAS média difere entre o grupo tratado e o controle?","A diferença de médias com IC é a informação principal. O d de Cohen expressa a diferença em desvios padrão: 0,2 pequeno, 0,5 médio, 0,8 grande (referências genéricas).","Arraste o tamanho da amostra no mundo simulado e veja quanto n é preciso para detectar diferenças pequenas."),
t_mw:TL("Mann-Whitney","Compara dois grupos independentes usando os postos: testa se os valores de um grupo tendem a ser maiores que os do outro.","H₀: a probabilidade de um valor de um grupo superar um do outro é 50%.","Dados assimétricos, ordinais (escalas de dor, Likert) ou com outliers, principalmente com amostras pequenas.","A dor (0–10) é menor com acupuntura do que com placebo?","U conta quantos pares têm o valor do grupo 1 maior que o do grupo 2. P(1 > 2) traduz isso em probabilidade, uma medida de efeito fácil de explicar.","Não é exatamente um teste de medianas: dois grupos com a mesma mediana, mas formas diferentes, podem dar p pequeno."),
t_tpar:TL("t pareado","Compara duas medidas feitas nas mesmas pessoas (antes e depois, olho direito e esquerdo).","H₀: a média das diferenças é zero.","Desfecho numérico medido duas vezes nos mesmos participantes; diferenças aproximadamente normais.","O colesterol mudou depois de um programa de exercícios?","O teste trabalha com as diferenças individuais. Como cada pessoa é comparada consigo mesma, a variação entre pessoas sai da conta, e o teste costuma ter muito mais poder que o t independente.","Experimente: troque para “t independente” mentalmente com os mesmos números; a variação entre pessoas tornaria a diferença muito mais difícil de detectar."),
t_wsr:TL("Wilcoxon pareado","Versão por postos do t pareado.","H₀: as diferenças estão distribuídas simetricamente em torno de zero.","Medidas pareadas com diferenças assimétricas, ordinais ou com outliers.","A ansiedade (0–40) diminuiu após a terapia?","V soma os postos das diferenças positivas. Pares sem mudança são excluídos.",""),
t_mcn:TL("McNemar","Compara proporções de uma variável sim/não medida duas vezes nas mesmas pessoas.","H₀: a proporção é a mesma antes e depois (tantos mudam num sentido quanto no outro).","Desfecho binário pareado: antes e depois, dois testes diagnósticos na mesma pessoa.","A presença de sintomas diminuiu após o medicamento?","Só os pares que mudaram (discordantes) informam. Se quase todos que mudaram foram no mesmo sentido, o p é pequeno.","Com menos de 25 pares discordantes, use o p exato."),
t_anova:TL("ANOVA de uma via","Compara as médias de três ou mais grupos independentes de uma vez.","H₀: todas as médias são iguais. H₁: pelo menos uma difere.","Desfecho numérico e um fator com três ou mais grupos. Use a versão de Welch quando os DPs forem diferentes.","O colesterol difere entre as dietas A, B e C?","F compara a variação entre os grupos com a variação dentro deles. η² é a proporção da variação total explicada pelos grupos. Se o p for pequeno, as comparações par a par (com correção) mostram onde está a diferença.","Não faça vários testes t sem correção: a chance de falso positivo cresce."),
t_kw:TL("Kruskal-Wallis","Versão por postos da ANOVA para três ou mais grupos independentes.","H₀: os grupos vêm da mesma distribuição.","Dados assimétricos, ordinais ou com outliers em três ou mais grupos.","O tempo de internação difere entre três hospitais?","H compara os postos médios dos grupos. Se o p for pequeno, as comparações par a par com correção indicam quais grupos diferem.",""),
t_rm:TL("ANOVA de medidas repetidas","Compara três ou mais medidas feitas nas mesmas pessoas.","H₀: as médias em todos os momentos são iguais.","Desfecho numérico medido em três ou mais momentos (ou condições) nos mesmos participantes.","A PAS muda entre 0, 3 e 6 meses de tratamento?","Como no t pareado, a variação entre pessoas é separada, o que aumenta o poder.","Softwares aplicam correção de esfericidade (Greenhouse-Geisser); esta versão didática não aplica."),
t_fr:TL("Friedman","Versão por postos da ANOVA de medidas repetidas.","H₀: a distribuição é a mesma em todos os momentos.","Três ou mais medidas nas mesmas pessoas, com dados ordinais ou assimétricos.","A dor muda entre o início, 1 semana e 4 semanas?","Os valores de cada pessoa são ordenados entre os momentos; o teste verifica se algum momento tende a ter postos maiores.",""),
t_pear:TL("Correlação de Pearson","Mede a força e a direção da relação <b>linear</b> entre duas variáveis numéricas.","H₀: a correlação na população é zero (ρ = 0).","Duas variáveis numéricas, relação aproximadamente linear, sem outliers extremos.","Atividade física e colesterol estão relacionados?","r vai de −1 a 1. r² é a proporção da variação compartilhada. Arraste um ponto para longe e veja como um único outlier muda r.","Correlação não é causalidade. Uma relação em U pode ter r perto de zero: olhe sempre o gráfico."),
t_spear:TL("Correlação de Spearman","Correlação calculada sobre os postos: mede relação monotônica (sempre crescente ou sempre decrescente).","H₀: não há associação monotônica.","Variáveis ordinais, relações curvas mas monotônicas, ou presença de outliers.","Dor (0–10) e número de sessões de fisioterapia estão relacionados?","ρ vai de −1 a 1. Compare com o r de Pearson no exemplo com outlier: Spearman resiste melhor.",""),
t_lin:TL("Regressão linear simples","Ajusta uma reta para prever Y a partir de X.","H₀: a inclinação da reta é zero (X não ajuda a prever Y).","Desfecho numérico e um preditor numérico, relação aproximadamente linear.","Quanto o estresse muda a cada hora a mais de sono?","b₁ é a mudança média em Y para cada unidade de X. R² é a proporção da variação de Y explicada. O gráfico de resíduos deve parecer uma nuvem sem padrão.","Com mais preditores (regressão múltipla), o b de cada variável fica ajustado pelas outras. A lógica é a mesma."),
t_log:TL("Regressão logística simples","Modela a probabilidade de um desfecho sim/não em função de uma variável X. O resultado é uma curva em S.","H₀: X não está associada ao desfecho (OR = 1).","Desfecho binário e um preditor numérico (ou vários, na regressão múltipla).","O IMC está associado ao diabetes?","A OR diz quanto a chance (odds) do desfecho se multiplica a cada unidade de X. Para 10 unidades, eleve a OR a 10.","OR não é risco relativo: com desfechos frequentes, a OR exagera a associação."),
t_chi:TL("Qui-quadrado","Testa a associação entre duas variáveis categóricas numa tabela de contingência.","H₀: as variáveis são independentes (a proporção do desfecho é a mesma em todas as linhas).","Duas variáveis categóricas, observações independentes, valores esperados ≥ 5.","Sedentarismo está associado à glicemia alta?","χ² soma as diferenças entre observado e esperado. Em tabelas 2 × 2, a razão de proporções (RP ou RR) e a odds ratio com IC dizem o tamanho da associação.","Com valores esperados pequenos, use Fisher. Para dados pareados, McNemar."),
t_fisher:TL("Exato de Fisher","Calcula a probabilidade exata de tabelas tão ou mais extremas que a observada, com os totais fixos.","H₀: não há associação entre linhas e colunas.","Tabelas 2 × 2 com valores esperados pequenos (amostras pequenas).","Numa amostra pequena, a exposição está associada à doença?","As barras mostram todas as tabelas possíveis com os mesmos totais. O p soma as tão ou menos prováveis que a observada.",""),
t_km:TL("Kaplan-Meier e log-rank","Estima a curva de sobrevida (proporção ainda sem o evento ao longo do tempo) e compara curvas entre grupos.","H₀ do log-rank: as curvas de sobrevida dos grupos são iguais.","Tempo até um evento (óbito, recidiva, alta), com participantes que saem do estudo antes do evento (censura).","A sobrevida é maior com o medicamento?","A mediana de sobrevida é o tempo em que a curva cruza 50%. O hazard ratio (Cox) resume a diferença de risco instantâneo: HR 0,5 significa metade do risco a cada momento.","Não calcule a média do tempo ignorando os censurados: isso subestima a sobrevida."),
});
/* ===================== GLOSSÁRIO ===================== */
const GLOSS=[
 ["Descrever os dados",[
  ["n","Tamanho da amostra","Número de observações (pessoas, medidas) analisadas."],
  ["x̄","Média amostral","Soma dos valores dividida por n. Lê-se “x barra”."],
  ["Md","Mediana","Valor do meio depois de ordenar os dados: metade fica abaixo, metade acima."],
  ["Mo","Moda","Valor mais frequente."],
  ["DP · s","Desvio padrão","Quanto os valores se afastam da média, em média. Mesma unidade dos dados."],
  ["s²","Variância","O desvio padrão ao quadrado. Na amostra, divide-se por n − 1."],
  ["Q1 · Q3","Primeiro e terceiro quartis","Valores abaixo dos quais ficam 25% e 75% dos dados."],
  ["IIQ","Intervalo interquartil","Q3 − Q1: a amplitude dos 50% centrais. Pouco afetado por outliers."],
  ["CV","Coeficiente de variação","DP ÷ média × 100. Compara dispersões de grupos com médias diferentes."],
  ["z","Escore z","(valor − média) ÷ DP: quantos desvios padrão um valor está da média."]]],
 ["População e amostra",[
  ["μ","Média da população","Lê-se “mi”. Valor verdadeiro que queremos estimar com x̄."],
  ["σ","Desvio padrão da população","Lê-se “sigma”. Estimado pelo DP da amostra."],
  ["p · p̂","Proporção","Fração com a característica. O chapéu (p̂) indica que é estimada na amostra."],
  ["EP","Erro padrão","DP ÷ √n. Mede a precisão da média amostral, não a variação entre pessoas."],
  ["IC 95%","Intervalo de confiança de 95%","Faixa de valores compatíveis com os dados. O método acerta o valor verdadeiro em 95% das vezes."],
  ["TCL","Teorema Central do Limite","Médias de amostras grandes se distribuem de forma aproximadamente normal, seja qual for a população."],
  ["Φ","Função da normal padrão","Área à esquerda de um valor z na curva normal. Lê-se “fi”."]]],
 ["Teste de hipótese",[
  ["H₀","Hipótese nula","A hipótese de que não há diferença, efeito ou associação."],
  ["H₁","Hipótese alternativa","A hipótese de que há diferença, efeito ou associação."],
  ["p","Valor de p","Probabilidade de obter dados tão ou mais extremos que os observados se H₀ fosse verdadeira. Não é a probabilidade de H₀ ser verdadeira."],
  ["α","Nível de significância (alfa)","Limite fixado antes do estudo, em geral 0,05. É a chance aceita de erro tipo I."],
  ["β","Erro tipo II (beta)","Chance de não detectar um efeito que existe."],
  ["1 − β","Poder","Chance de detectar um efeito que existe. Planeja-se em geral 80% a 90%."],
  ["gl","Graus de liberdade","Número de valores livres para variar no cálculo. Define o formato das distribuições t, F e χ²."],
  ["Δ","Delta: diferença","Usado para diferenças entre grupos ou para o efeito mínimo clinicamente importante."],
  ["n.s.","Não significativo","p ≥ α. Não quer dizer “sem efeito”: olhe o intervalo de confiança."],
  ["P(A | B)","Probabilidade condicional","Probabilidade de A entre os que têm B. Lê-se “A dado B”."]]],
 ["Estatísticas dos testes",[
  ["t","Estatística t","Diferença observada dividida pelo seu erro padrão. Usada nos testes t e na regressão."],
  ["F","Estatística F","Razão entre a variação entre grupos e a variação dentro dos grupos (ANOVA)."],
  ["χ²","Qui-quadrado","Soma de (observado − esperado)² ÷ esperado. Também usada no log-rank, Kruskal-Wallis e Friedman."],
  ["U","U de Mann-Whitney","Conta quantos pares têm o valor de um grupo maior que o do outro."],
  ["V","V de Wilcoxon","Soma dos postos das diferenças positivas."],
  ["H","H de Kruskal-Wallis","Compara os postos médios de três ou mais grupos."],
  ["W","W de Shapiro-Wilk","Quanto os dados se parecem com uma normal (1 = perfeitamente normal)."],
  ["posto","Posto (rank)","Posição do valor depois de ordenar os dados. Base dos testes não paramétricos."]]],
 ["Tamanho de efeito e associação",[
  ["d","d de Cohen","Diferença de médias em unidades de desvio padrão. Referências genéricas: 0,2 pequeno, 0,5 médio, 0,8 grande."],
  ["r","Correlação de Pearson","Força e direção da relação linear, de −1 a 1."],
  ["ρ","Rho de Spearman","Correlação calculada com os postos. Lê-se “rô”."],
  ["r² · R²","Coeficiente de determinação","Proporção da variação de Y explicada por X."],
  ["b₀ · b₁","Coeficientes da regressão","b₀ é o intercepto (Y quando X = 0); b₁ é a inclinação (mudança em Y por unidade de X)."],
  ["η²","Eta ao quadrado","Proporção da variação explicada pelos grupos na ANOVA."],
  ["RR","Risco relativo","Risco nos expostos ÷ risco nos não expostos. 1 = sem associação."],
  ["RP","Razão de prevalências","Como o RR, mas com prevalências, em estudos transversais."],
  ["OR","Odds ratio (razão de chances)","Chance nos expostos ÷ chance nos não expostos. Exagera o RR quando o desfecho é frequente."],
  ["HR","Hazard ratio","Razão entre os riscos instantâneos de evento ao longo do tempo (regressão de Cox)."],
  ["RD","Diferença de riscos","Risco nos expostos − risco nos não expostos. Base do NNT."]]],
 ["Nomes de testes e métodos",[
  ["ANOVA","Análise de variância","Compara médias de três ou mais grupos."],
  ["MR","Medidas repetidas","Mesmas pessoas medidas em vários momentos."],
  ["KM","Kaplan-Meier","Método para estimar curvas de sobrevida com censura."],
  ["censura","Dado censurado","Participante que saiu do estudo sem ter o evento; sabemos só que sobreviveu até ali."],
  ["Holm · Bonferroni","Correções para múltiplas comparações","Ajustam o p quando vários testes são feitos, para controlar falsos positivos."]]],
];
function openGloss(){openSheet("Glossário",`<input class="gsearch" id="gq" placeholder="Buscar: alfa, IC, odds…" aria-label="Buscar no glossário"><div id="gList"></div>`);
  const norm=t=>t.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,""),alias={"alfa":"α","beta":"β","mi":"μ","sigma":"σ","rho":"ρ","qui":"χ²","eta":"η²","delta":"Δ","fi":"φ"};
  const draw=q=>{const n=norm(q.trim());$("gList").innerHTML=GLOSS.map(([cat,items])=>{const f=items.filter(it=>!n||norm(it.join(" ")).includes(n)||Object.entries(alias).some(([k,v])=>k.startsWith(n)&&it[0].includes(v)));return f.length?`<div class="gcat">${cat}</div>`+f.map(([s,t,d])=>`<div class="gl"><span class="sy">${s}</span><div><b>${t}</b><p>${d}</p></div></div>`).join(""):"";}).join("")||`<p class="note">Nada encontrado. Tente outro termo.</p>`;};
  draw("");$("gq").addEventListener("input",e=>draw(e.target.value));}
